language: scala

jdk:
  - openjdk8

before_install:
  - git fetch --tags

install:
  - rvm use 2.6.5 --install --fuzzy
  - gem install jekyll -v 4

stages:
  - name: test
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork

jobs:
  include:
    # stage="test" if no stage is specified
    - name: test 2.13 & jdk11
      scala: [ 2.13.3 ]
      jdk: openjdk11
      script: sbt ++$TRAVIS_SCALA_VERSION test
    - name: test 2.13 & jdk8
      scala: [ 2.13.3 ]
      jdk: openjdk8
      script: sbt ++$TRAVIS_SCALA_VERSION test
    - name: test 2.12 & jdk11
      scala: [ 2.12.12 ]
      jdk: openjdk11
      script: sbt ++$TRAVIS_SCALA_VERSION test
    - name: test 2.12 & jdk8
      scala: [ 2.12.12 ]
      jdk: openjdk8
      script: sbt ++$TRAVIS_SCALA_VERSION test
    - name: coverage
      scala: [ 2.13.3 ]
      jdk: openjdk11
      script: sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport
    # run ci-release only if previous stages passed
    - stage: release
      name: release
      jdk: openjdk8
      script: sbt ci-release makeMicrosite

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
